question_data = [
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Igneous rocks are formed by excessive heat and pressure.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "French is an official language in Canada.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Books",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Activision created Battlefield 1.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "An equilateral triangle always has every angle measuring 60&deg;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
